#pragma once

#include "Definition.h"
#include "Class.h"
#include "Diagnosis.h"
#include "Utility.h"
#include "Algorithm.h"
#include "Hash.h"
#include "Tuple.h"
#include "UnifiedPtr.h"
#include "Reference.h"
#include "Exception.h"
#include "Memory.h"
#include "Array.h"
#include "Nullable.h"
#include "Variant.h"
#include "RBTree.h"
#include "AVLTree.h"
#include "Stack.h"
#include "LinearMemoryManager.h"
#include "Linq.h"
#include "List.h"
#include "BloomFilter.h"
#include "Delegate.h"
#include "ThreadingDefine.h"
#include "SPSCQueue.h"
#include "Lock.h"
#include "ConditionVariable.h"
#include "Thread.h"
#include "ConcurrentStack.h"
#include "GarbageCollector.h"
#include "Task.h"
#include "Dictionary.h"
#include "CharSet.h"
#include "String.h"
#include "TextWriter.h"
#include "File.h"
#include "Json.h"
#include "JsonForStandard.h"
#include "RegexParser.h"
#include "Regex.h"
#include "NewRegex.h"

//Runtime Part 
#include "RuntimeAlias.h"
#include "NormalizedType.h"
#include "TypeDescriptor.h"

#include "ClassLoader.h"
#include "TypeHandle.h"
#include "EEClass.h"
#include "ArrayClass.h"
#include "DelegateClass.h"

#include "MethodTable.h"
#include "ManagedObject.h"


#include "OpCode.h"
#include "ExecutablePage.h"
#include "WindowsExecutablePage.h"
#include "Emitter.h"
#include "Binary.h"
#include "X86Emitter.h"
#include "JIT.h"
#include "HexJIT.h"


